### PR TITLE
Conditional tabs in filtering tab

### PR DESCRIPTION
**Pull request by Cristianetaniguti**
* Add conditional tabs for Filtering tab
* Add legend for the plot dashed lines
* Improve testing for Filtering tab

### CODE REVIEW

**Comment by alex-sandercock** [comment]
The conditional tabs are excellent. Could you ensure that a box is there prior to the plots appearing. Currently, there is a blank space on the filtering page where the plots appear after filtering.

- The checks are failing for this newest update

**Review by alex-sandercock — CHANGES_REQUESTED** [review]
I added some information in the posted comment.

**Comment by Cristianetaniguti** [comment]
* tests fixed
* placeholder tab added to avoid empty space

**Review by alex-sandercock — COMMENTED** [review]
Looks good

**Pull request merged**
